Add public API to enable "debug" logs of Console handler
criteo/android-publisher-sdk pull request #156
Opened 2020-11-24 10:40 UTC by TurpIF

JIRA: EE-1343

2020-11-24 14:40 UTC, TurpIF commented
Note that the code coverage is low because tests on `withSpiedLogger` lives in `publisher-sdk` module because it needs access to the `ConsoleHandler` which is `internal`. It is nitpicking, but I added EE-1370 to try to get the true coverage on `test-utils` module.

2020-11-25 09:00 UTC, Amokrane requested changes

2020-11-25 12:46 UTC, TurpIF commented on publisher-sdk/src/main/java/com/criteo/publisher/logging/ConsoleHandler.kt
> +    Log.println(level, "Crto$tag", message)
It is put in a constant in https://github.com/criteo/android-publisher-sdk/pull/158 (commit: https://github.com/criteo/android-publisher-sdk/pull/158/commits/794c8336699aaa66d8e7e6fde238d44b76da0025)

2020-11-25 12:49 UTC, TurpIF commented on publisher-sdk/src/main/java/com/criteo/publisher/logging/ConsoleHandler.kt
> +    logMessage.message
It's an old habitude I had when dealing with `Stream`: generally you have newlines aligned to clearly see the operation (`map`, `filter`, ...) and the lambda.

Let me change this then.

2020-11-26 09:29 UTC, Amokrane approved these changes

2020-11-30 11:20 UTC, merged